language: python

services:
  - redis-server

stages:
  - lint
  - test
  - release

before_install:
  - pip install poetry

install:
  - poetry install -v

jobs:
  include:
    - stage: lint
      script:
        - poetry run pylint oauth_token_cache
        - poetry run black --check .
    - stage: test
      python:
        - "3.6"
        - "3.7"
      script:
        - poetry run pytest --cov=oauth_token_cache --cov-report term-missing test/
        - poetry run codecov
    - stage: release
      script: skip
      before_deploy:
        - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
        - poetry build -f sdist
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true
      if: tag IS present
