language: python

python:
  - 3.6
  - 3.7

services:
  - redis-server

stages:
  - lint
  - test
  - name: release
    if: tag IS present

install:
  - pip install poetry
  - poetry install -v

script:
  - make pytest

jobs:
  include:
    - stage: lint
      script:
        - poetry run pylint oauth_token_cache
        - poetry run black --check .
    - stage: test
      script:
        - make pytest
      after_success:
        - make codecov
    - stage: release
      python: 3.7
      script: skip
      before_deploy:
        - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
        - poetry build -f sdist
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true
