language: python

python:
- "3.6"
- "3.7"

services:
  - redis-server

stages:
  - lint
  - test
  - release

before_install:
  - pip install poetry tox-travis

install:
  - poetry install -v

jobs:
  include:
    - stage: lint
      script:
        - poetry run pylint oauth_token_cache
        - poetry run black --check .
    - stage: test
      script:
        - make tox
      after_success:
        - make codecov
    - stage: release
      script: skip
      before_deploy:
        - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
        - poetry build -f sdist
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true
          condition: "$TRAVIS_PYTHON_VERSION == 3.7"
      if: tag IS present
